global:
  scrape_interval: 60s  
  evaluation_interval: 60s 

  external_labels:
      monitor: prefect-surrogate-models

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 60s
    static_configs:
      - targets: 
        - localhost:9090

  - job_name: mlflow
    scrape_interval: 60s
    static_configs:
      - targets: 
        - 'mlflow:5000'

  - job_name: cadvisor
    scrape_interval: 60s
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: node-exporter
    scrape_interval: 60s
    static_configs:
      - targets: 
        - node-exporter:9100

  - job_name: minio-job-bucket
    scrape_interval: 60s
    metrics_path: /minio/v2/metrics/bucket
    scheme: http
    static_configs:
      - targets: 
        - minio:9000

  - job_name: minio-job-cluster
    scrape_interval: 60s
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: 
        - minio:9000
